--ZhiPu--
(自己)api_key:09e5da4addba0a593c33a3bf0992b01a.rsVrVkwiB5XZ8Ze
Model:GLM-4-Plus
end_time：2024-10-30 03:50:43

(右边兄弟)api_key:5f12e86015e0a1cfe113f50960bfcf0c.T6iNWxjOaztQXpeQ
Model:GLM-4-0520
end_time:忘了

(4元一个)api_key:4d177fa7b97da9d87007acf21b11f473.iqDWF4ZtKvs3JO1a
Model:GLM-4-Plus
end_time:2024-10-30 - 一个月
------------------------------------------------------------------------------------------------
--Gpt--
(实验室)api_key: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
(野生)api_key:ddd
Model:gpt-4o,gpt-4o-mini,o1-preview,o1-mini
end_time:随时可能没钱

------------------------------------------------------------------------------------------------

--QianWen--
(自己)api_key:sk-5735d37f3be1495f8261dea4a75c36ae
Model:qwen-max
end_time:已经没钱啦

------------------------------------------------------------------------------------------------

--Llama--
(自己)Llama-7b 已部署在服务器(模型参数，prompt不起作用)

(自己)llama3.1-405b-instruct,llama3.1-70b-instruct
api_key:sk-5735d37f3be1495f8261dea4a75c36ae
end_time:2025-01-21


