import numpy as np
# 假设你有一个包含所有响应内容的字符串
responses = """
response_test: Yes
response_test: No
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: No
response_test: Yes
response_test: No
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: No
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: No
response_test: Yes
response_test: No
response_test: No
response_test: No
response_test: No
response_test: No
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: No
response_test: Yes
response_test: No
response_test: Yes
response_test: No
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: No
response_test: Yes
response_test: No
response_test: Yes
response_test: No
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: No
response_test: No
response_test: No
response_test: No
response_test: Yes
response_test: Yes
response_test: Yes
response_test: No
response_test: Yes
response_test: No
response_test: No
response_test: No
response_test: No
response_test: No
response_test: No
response_test: No
response_test: No
response_test: Yes
response_test: No
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: No
response_test: No
response_test: Yes
response_test: No
response_test: No
response_test: No
response_test: No
response_test: Yes
response_test: No
response_test: Yes
response_test: No
response_test: Yes
response_test: Yes
response_test: No
response_test: No
response_test: No
response_test: Yes
response_test: No
response_test: No
response_test: No
response_test: No
response_test: Yes
"""

# 将响应内容拆分成列表
response_lines = responses.strip().split('\n')

# 定义一个空列表来存储提取的内容
response_values = []

# 遍历每一行并提取冒号后的内容
for line in response_lines:
    # 拆分字符串并去掉两端的空格
    content = line.split(':')[1].strip()
    # 添加到列表中
    response_values.append(content)

# 打印提取的内容列表
print(response_values)